spring.application.name=oath2
spring.config.import=file:env.properties
spring.security.oauth2.client.registration.github.clientId=${CLIENT_ID}
spring.security.oauth2.client.registration.github.clientSecret={CLIENT_SEC}
